#!/usr/bin/env bash
# A script that displays information about subdomains

domain=$1
subdomain=("$2")

if [ "${#subdomain[0]}" -eq 0 ]
then
	subdomain=(www lb-01 web-01 web-02)
fi

function domain_info() 
{
	for sub in "${subdomain[@]}"
	do
		fulldomain="${sub}.${domain}"
		rec_typ=$(dig "$fulldomain" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk '{print$4}')
		destination=$(dig "$fulldomain" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk '{print$5}')
		echo "The subdomain $sub is a $rec_typ record and points to $destination"
	done
}

domain_info
