#!/usr/bin/env bash
# sending file to remote server fix

FILE=$1
IP=$2
USER=$3
SSH_KEY=$4
ARGV=$#

if [ $ARGV -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USER@$IP:~/"
