#!/usr/bin/env bash
#Installation and configuration of Nginx

sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo Hello World > /var/www/html/index.html'
service nginx restart
