#!/usr/bin/env bash
# Creates a redirect

service nginx start
sed '/server_name _/a location /redirect_me { \
			return 301 https://www.linkedin.com/in/valentine-chidubem-9a076620a;\
			}' /etc/nginx/sites-available/default
service nginx restart
