#!/usr/bin/env bash
# Installing Nginx
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/valentine-chidubem-9a076620a;\n\t}" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/server_name/a \\\n\terror_page 404 404.html" /etc/nginx/sites-available/default
service nginx restart
