#!/usr/bin/env bash
# Creates a redirect

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -n -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/valentine-chidubem-9a076620a;\n\t}" /etc/nginx/sites-available/default
sudo sh -c "echo Ceci n\'est pas une page > /var/www/html/404.html"
sudo sed -i "/server_name/a \\\n\terror_page 404 404.html" /etc/nginx/sites-available/default
service nginx restart
