#!/usr/bin/env bash
#installing and configuring load balancers
sudo apt-get update -y
sudo apt-get install haproxy -y
sudo service haproxy start
sudo sed -i "/504.http/a \
	\\\n\nbackend myservers\
	\n\tbalance roundrobin\
	\n\tserver 9084-web-01 3.230.166.53\
	\n\tserver 9084-web-02 3.238.228.250\
	\n\nfrontend myfrontend\
	\n\tbind *:80\
	\n\tmode http\
	\n\tdefault_backend myservers" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
