#!/usr/bin/env bash
# usage of while loops in bash

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -ne 9 ]
    then
        echo "Best School"
    else
        echo "Hi"
    fi
    (( counter++ ))
done
